## Revisão Numpy

In [1]:
import numpy as np

In [2]:
my_array = np.arange(1000000)
my_array

array([     0,      1,      2, ..., 999997, 999998, 999999])

In [5]:
my_list = list(range(1000000))

In [6]:
data = np.random.randn(2,3)

## 4.1 O NumPy ndarray: Um Objeto de Matriz Multidimensional

Uma das principais características do NumPy é seu objeto de matriz N-dimensional, ou ndarray,
que é um contêiner rápido e flexível para grandes conjuntos de dados no Python. Arrays permitem que você
executar operações matemáticas em blocos inteiros de dados usando uma sintaxe semelhante à
operações equivalentes entre elementos escalares.
Para dar uma ideia de como o NumPy permite cálculos em lote com sintaxe semelhante
para valores escalares em objetos Python internos, primeiro importo o NumPy e gero um pequeno
matriz de dados aleatórios:

In [7]:
data

array([[ 0.87242136,  0.77957901, -1.18259032],
       [ 0.75478112, -0.31266079,  1.51665465]])

Operações matematicas com python

In [8]:
data * 2

array([[ 1.74484272,  1.55915801, -2.36518065],
       [ 1.50956225, -0.62532157,  3.03330929]])

In [9]:
data +  data

array([[ 1.74484272,  1.55915801, -2.36518065],
       [ 1.50956225, -0.62532157,  3.03330929]])

In [15]:
data.shape

(2, 3)

In [16]:
data.dtype

dtype('float64')

In [17]:
data1 = [1,7.5,8,0,1]

In [19]:
data1

[1, 7.5, 8, 0, 1]

In [20]:
arr1 = np.array(data1)

In [21]:
arr1

array([1. , 7.5, 8. , 0. , 1. ])

In [22]:
data2 = [[1,2,3,4],[5,6,7,8]]

In [23]:
arr2 = np.array(data2)

In [24]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [25]:
arr2.ndim

2

In [26]:
arr2.shape

(2, 4)

In [27]:
arr1.dtype

dtype('float64')

In [28]:
arr2.dtype

dtype('int32')

In [29]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [31]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [32]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr